### ISSUE TITLE
Where is nircmd.exe from?

### ISSUE THREAD

**Issue by joelewiss** [rex-mcall/Annoying-Computer-Program#2]
Hey Rex,

Cool program. Where is [nircmd.exe](https://github.com/rex-mcall/Annoying-Computer-Program/blob/master/Batch/lib/nircmd.exe) from? 

Maybe you could write a C app that does the same thing with something like [DirectShow](https://docs.microsoft.com/en-us/windows/win32/directshow). It has its own [eject method](https://docs.microsoft.com/en-us/windows/win32/directshow/eject-method) for dvd drivers.

**Comment by rex-mcall** [comment]
Hi Joe,
I found nircmd.exe from someone on a StackExchange forum. It's an easy way
to control various aspects of the computer from the command line
<https://www.nirsoft.net/utils/nircmd.html>. Also, thanks for the link to
DirectShow, I will definitely check it out.

-RMcA

**Comment by joelewiss** [comment]
Oh cool. Let me know how directshow goes, it seems like there's some pretty cool stuff in there.
